version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: salesgpt-backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    networks:
      - salesgpt-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: salesgpt-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_API=http://backend:8000
      # - NEXT_PUBLIC_SUPABASE_URL=https://rnlqhsbkugnamwlskgfl.supabase.co
      # - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOi
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - salesgpt-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: salesgpt-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - salesgpt-network
    restart: unless-stopped

networks:
  salesgpt-network:
    driver: bridge

volumes:
  mongodb_data: